run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - revive
    - gofmt
    - goimports
    - misspell
    - gocritic

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
